import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer_profile.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Alex</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="portfolio photo"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Превращаем идеи в реальность с помощью кода и дизайна."
                className="!text-5xl !text-left mb-2"
              />
              <p className="my-4 text-base font-medium">
                Я стремлюсь превращать идеи в инновационные веб-приложения.
                Изучите мои последние проекты и статьи, демонстрирующие мой
                опыт в React.js и веб-разработке.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Аввакумов_Александр_Frontend_developer.pdf"
                  target={'_blank'}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark transition-all duration-200 ease-in-out"
                  download={true}>
                  Резюме <LinkArrow className={'w-6 ml-1'} />
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 innline-block w-24">
          <Image src={lightBulb} alt="name" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
